### ISSUE TITLE
fix prebuilds

### ISSUE THREAD

**Issue by contra** [contra/node-gdal-next#1]
Last thing that needs to be done is fixing the CI process.

Currently broken:

- Windows
  - https://ci.appveyor.com/project/contra/node-gdal-next/builds/30755364/job/ib61kph7q13qrlwj#L1199
- Linux
  - https://travis-ci.org/contra/node-gdal-next/builds/649559608

Currently working:

- All mac builds

**Comment by jdesboeufs** [comment]
My last Linux build were sucessful:
https://travis-ci.org/jdesboeufs/node-gdal/builds/622911781

Maybe some changes to pick.
Will look at this ASAP.

**Comment by contra** [comment]
@jdesboeufs Thanks! Really appreciate the help. I have been making tweaks to get the windows builds working and have it pretty close, probably needs another hour or two to finish it up - I'll take ownership of getting the windows builds finished up.

**Comment by contra** [comment]
Update on this:

- Travis CI: All builds are working except for Linux from source
  - I think the issue is linker related, not sure what's going on here yet - would appreciate some help. `undefined symbol: OGRDXFLayer::TranslateMLEADER()`
  - https://travis-ci.org/contra/node-gdal-next/builds/658023018
- Appveyor: Some file functions are missing, cpl file is not valid
  - https://ci.appveyor.com/project/contra/node-gdal-next/builds/31224931/job/3tqm6c3gktmdmr35#L1148

**Comment by contra** [comment]
Good news! Everything on travis is passing (Node 10/11/12/13) - even after doing a load of changes and upgrades to the build process (upgrading G++, moved around a lot of linker settings, etc.).

Only windows needs to be done now - still working on that.

**Comment by contra** [comment]
More good news - just got windows working. All items on the roadmap are finished and this is ready to publish. https://ci.appveyor.com/project/contra/node-gdal-next/builds/31243623

@jdesboeufs Anything else you want to see or are we good to publish a v2.0.0 on the gdal-next package you own? Will just need to set up the prebuilt publishing S3 - I can pay for the storage if you'd like.
