### ISSUE TITLE
Cannot find proj.db

### ISSUE THREAD

**Issue by claustres** [contra/node-gdal-next#2]
Thanks for this fork as we are happy trying to migrate some of our projects on Node v12 !

For instance https://github.com/weacast/weacast-gtiff2json seems to work well.

However we have an issue migrating https://github.com/kalisio/krawler where we use the GDAL binding to perform [coordinates transformation](https://github.com/kalisio/krawler/blob/master/src/hooks/hooks.raster.js#L106). In that case, when upgrading to your fork then running our tests, we get this error: `Error: PROJ: proj_create_from_database: Cannot find proj.db`.

As we did not have this issue previously I wonder if this is related to some setup we need to update like GDAL_DATA or PROJ_LIB or to your package directly.

Thanks again for your feedback.

**Comment by contra** [comment]
@claustres What OS are you having the issue on? We set the env var here by default which should get picked up by gdal https://github.com/contra/node-gdal-next/blob/master/lib/gdal.js#L22 but I have heard mixed messages that this may not work on windows.

Also - make sure you're on the latest version - I fixed an issue with that env var not being set correctly in one of the earlier patch releases.

**Comment by claustres** [comment]
Yes I am using Node.js 12 under Windows 10, we also have a travis build under Linux which seems to be fine, so this could be related.

**Comment by contra** [comment]
@claustres Hmm... Can you try to manually set the env var to this value https://github.com/contra/node-gdal-next/blob/master/lib/gdal.js#L7 and see if that fixes it? If so we can confirm it is an env issue on windows and I can look into a fix for it.

**Comment by claustres** [comment]
Sorry for the delay, just tested this morning and I confirm this fixes the issue.

**Comment by contra** [comment]
This might be a tricky one to fix - I don't have any ideas off the top of my head. We can't build this in at compile because the relative path isn't the same at build time and install time, but also can't use ENV to set it.

One kind of messy option is to add a  function into PROJ for manipulating it programmatically (similar to how this works in GDAL for setting GDAL_DATA), so we have that on the table. I would prefer not do to that because it's one more patch to keep maintained when updating libroj.

**Comment by claustres** [comment]
I don't see it as a bug, the docs should maybe just specify that under Windows or some cases you need to set the env var manually.

**Comment by contra** [comment]
@claustres Were you able to set the env to a relative path? Could you paste the value and I'll add it to the docs until we have a workaround.

**Comment by claustres** [comment]
No I used an absolute path, what is strange is that if I remove my env var and console.log the env var when launching my module it is still set so that your module is correctly changing it, and the path is absolutely the same than the one I set in the env var. Maybe it is related to the initialization order and some operation require the env var before it is correctly set ?

**Comment by contra** [comment]
@claustres The issue is that ENV isn't able to be set by node (in windows only) in a way that the native C code can access it - the value is changed within the node context but nowhere else.

**Comment by claustres** [comment]
ok got it, some docs update seems the way to go ;-)

**Comment by olivierchatry** [comment]
One way would be to directly call `OSRSetPROJSearchPaths` and not rely on the `PROJ_LIB` environment variable in case the built-in version of gdal is used ?

**Comment by olivierchatry** [comment]
Added a pull request https://github.com/contra/node-gdal-next/pull/32 @contra if you want to take a look.
