### ISSUE TITLE
Raster async functions throw synchronously when the arguments are invalid

### ISSUE THREAD

**Issue by mmomtchev** [contra/node-gdal-next#37]
If an error is detected during the parsing of the arguments phase (the synchronous phase), the raster async functions with throw a synchronous error when called with a callback (as opposed to Promise).
I/O errors are reported via the callback and the Promisified-versions work as they should - by rejecting the Promise whether the error is during the synchronous or the asynchronous phase.

The callback versions should report errors only through the callback as it is the norm in all standard Node.js libraries

**Comment by mmomtchev** [comment]
In fact, some standard libraries do exhibit the same behaviour... ok, maybe this will stay like this for the time being

**Comment by contra** [comment]
I think this behavior is valid - if the error is with arguments and not execution of work it should be thrown in the main thread, since it is the main threads problem for invoking with invalid arguments.
