### ISSUE TITLE
FlattenTo2D method for geometry object

### ISSUE THREAD

**Issue by alperdincer** [contra/node-gdal-next#48]
I'm dealing with some layers that has 3d and this will cause problems with geometry columns in Oracle Database. I checked for forcing geometry to 2d but I can't find any method for it. But GDAL bindings for Python has the FlattenTo2D() method for geometry to do this job and how can we added to this library?

**Comment by contra** [comment]
@alperdincer Should be a relatively easy function to expose - let me look into it and I'll get back to you on it.
