### ISSUE TITLE
LCC projections support broken

### ISSUE THREAD

**Issue by jdesboeufs** [contra/node-gdal-next#6]
The support of LCC projections seems to be broken since PROJ6 integration.
So I'm stuck to `0.10.0` version in production for now.

Example code:

```js
const gdal = require('gdal-next')

const wgs84 = gdal.SpatialReference.fromProj4('+init=epsg:4326')

const dataset = gdal.open('/vsizip/test.zip')
const layer = dataset.layers.get(0)
const transform = new gdal.CoordinateTransformation(layer.srs, wgs84)

const geometry = layer.features.get(0).getGeometry()
geometry.transform(transform)
```

You can try with this file:
```bash
curl https://www.data.gouv.fr/fr/datasets/r/1cbb1e3a-b915-4103-95ad-6a9feb3c8187 > test.zip
```

**Comment by contra** [comment]
@jdesboeufs Could you make a repo that expresses this as a test using some assertions? Then I can run the tests against each version of gdal and look into the issue, and have a better idea of it actually being fixed without having to manually look at the output. I'm not super familiar with the expected output so will make it much easier.

**Comment by jdesboeufs** [comment]
After some additional research, it seems the transformation "Lambert Conformal Conic" used in the coordinates system is not supported anymore in PROJ7.
It also breaks with `ogr2ogr` 3.1.
It's a real problem for me, but it's not the responsability of `gdal-next`.

**Comment by jdesboeufs** [comment]
I reopen the issue since I'm able to "repair" the projection with `ogr2ogr`.
So if `ogr2ogr` is able to read and save, then open read and transform, `gdal-next` could too.

**Comment by mmomtchev** [comment]
@jdesboeufs this is working for me in the latest version, can you please retry and give me feedback

**Comment by jdesboeufs** [comment]
It's working!

Thank you very much!
