### ISSUE TITLE
Support for ogrlineref function

### ISSUE THREAD

**Issue by zhangjinzhou** [contra/node-gdal-next#9]
Do we have plan to include **ogrlineref** in this nodejs implementation?

**Comment by contra** [comment]
How do you see the API looking for this?

**Comment by zhangjinzhou** [comment]
@contra What do you mean? The gdal official has [the function](https://gdal.org/programs/ogrlineref.html). We are looking for the functionality in nodejs implementation to add new feature to our application.

**Comment by contra** [comment]
ogrlineref is a command line tool (like ogr2ogr) and not a function that we can expose in the nodejs binding. We would need to re-implement `ogrlineref` as a real interface to be able to bind to it. This library is a straight up link from JS to the native gdal libraries and doesn't intend to re-implement any of the command line tools that are bundled with the gdal library.

You can read the source code for ogrlineref here: https://github.com/OSGeo/gdal/blob/master/gdal/apps/ogrlineref.cpp

All of the same functions that the `ogrlineref` CLI uses are available in this binding, so you can reimplement whatever functionality you need from that in JS.

**Comment by zhangjinzhou** [comment]
@contra Thanks! Good to know. We usually run ogr2ogr tools with commandline tool in nodejs. I will do the same thing.
